//
// custom loot

// Not Used
  LootJS.modifiers(e => {
// TRINKETS & ARTIFACTS
  e.addLootTypeModifier(LootType.CHEST)
    .randomChance(0.40)
    .addWeightedLoot(
      [0, 2], //0-2 rolls
      [
  LootEntry.of("artifacts:pocket_piston").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:charm_of_sinking").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:shock_pendant").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:running_shoes").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:universal_attractor").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:anglers_hat").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:superstitious_hat").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:fire_gauntlet").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:crystal_heart").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:night_vision_goggles").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:vampiric_glove").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:thorn_pendant").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:plastic_drinking_hat").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:onion_ring").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:everlasting_beef").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:pickaxe_heater").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:rooted_boots").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:obsidian_skull").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:feral_claws").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:novelty_drinking_hat").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:helium_flamingo").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:lucky_scarf").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:bunny_hoppers").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:cloud_in_a_bottle").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:cross_necklace").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:chorus_totem").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:steadfast_spikes").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:golden_hook").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:kitty_slippers").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:antidote_vessel").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:snorkel").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:flame_pendant").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:whoopee_cushion").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:aqua_dashers").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:cowboy_hat").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:power_glove").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:digging_claws").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:villager_hat").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:panic_necklace").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:scarf_of_invisibility").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:flippers").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:umbrella").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:snowshoes").withWeight(15).limitCount([0, 1]),
  LootEntry.of("artifacts:eternal_steak").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:iron_ring").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:monster_charm").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:super_magnet_ring").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:golden_ring").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:mining_charm").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:cursed_ring").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:mega_sponge").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:ascension_amulet").withWeight(1).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:xp_scroll").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:ender_ring").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:magnet_ring").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:heaven_scroll").withWeight(10).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:fabulous_scroll").withWeight(10).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:enigmatic_eye").withWeight(1).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:extradimensional_eye").withWeight(15).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:enigmatic_amulet").withWeight(5).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:enigmatic_item").withWeight(1).limitCount([0, 1]),
  LootEntry.of("enigmaticlegacy:infinimeal").withWeight(1).limitCount([0, 1]),
      ]);

// USEFUL LOOT
  e.addLootTypeModifier(LootType.CHEST)
    .randomChance(0.70)
    .addWeightedLoot(
      [0, 2], //0-2 rolls
      [
  LootEntry.of("advancementframes:advancement_frame").withWeight(50).limitCount([0, 1]),
  LootEntry.of("advancementframes:stat_frame").withWeight(50).limitCount([0, 1]),
  LootEntry.of("apotheosis:common_material").withWeight(70).limitCount([0, 1]),
  LootEntry.of("apotheosis:mythic_material").withWeight(40).limitCount([0, 1]),
  LootEntry.of("apotheosis:rare_material").withWeight(60).limitCount([0, 1]),
  LootEntry.of("apotheosis:epic_material").withWeight(50).limitCount([0, 1]),
  LootEntry.of("apotheosis:uncommon_material").withWeight(50).limitCount([0, 1]),
  LootEntry.of("pipez:basic_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("pipez:advanced_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("pipez:improved_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("pipez:ultimate_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:tool_swapper_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_magnet_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:anvil_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:restock_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_restock_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_pump_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:chipped/botanist_workbench_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_filter_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:void_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:chipped/glassblower_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:netherite_backpack").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:pickup_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:compacting_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:auto_smelting_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:chipped/loom_table_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:chipped/tinkering_table_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:jukebox_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:diamond_backpack").withWeight(5).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_tool_swapper_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:stonecutter_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:smoking_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_feeding_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:backpack").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:pump_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_pickup_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_deposit_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_void_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_compacting_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:iron_backpack").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:stack_upgrade_tier_2").withWeight(5).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:stack_upgrade_tier_3").withWeight(5).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:stack_upgrade_tier_1").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:stack_upgrade_tier_4").withWeight(5).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:chipped/mason_table_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:stack_upgrade_starter_tier").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:deposit_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:upgrade_base").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:chipped/carpenters_table_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:feeding_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:copper_backpack").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:everlasting_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:gold_backpack").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:chipped/alchemy_bench_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:advanced_refill_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:auto_smoking_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:smelting_upgrade").withWeight(5).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:inception_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:tank_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:auto_blasting_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:refill_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:xp_pump_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:filter_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:crafting_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:magnet_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:blasting_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("sophisticatedbackpacks:battery_upgrade").withWeight(15).limitCount([0, 1]),
  LootEntry.of("apotheosis:ender_library").withWeight(5).limitCount([0, 1]),
  LootEntry.of("apotheosis:library").withWeight(15).limitCount([0, 1]),
  LootEntry.of("botania:dice").withWeight(1).limitCount([0, 1]),
  LootEntry.of("mythicbotany:mjoellnir").withWeight(1).limitCount([0, 1]),
  LootEntry.of("tempad:he_who_remains_tempad").withWeight(1).limitCount([0, 1]),
  LootEntry.of("powah:furnator_basic").withWeight(35).limitCount([0, 1]),
  LootEntry.of("powah:thermo_generator_basic").withWeight(35).limitCount([0, 1]),
  LootEntry.of("powah:furnator_starter").withWeight(35).limitCount([0, 1]),
  LootEntry.of("powah:solar_panel_starter").withWeight(35).limitCount([0, 1]),
  LootEntry.of("powah:magmator_basic").withWeight(35).limitCount([0, 1]),
  LootEntry.of("powah:solar_panel_basic").withWeight(35).limitCount([0, 1]),
  LootEntry.of("powah:thermo_generator_starter").withWeight(35).limitCount([0, 1]),
  LootEntry.of("powah:magmator_starter").withWeight(35).limitCount([0, 1]),
  LootEntry.of("powah:furnator_basic").withWeight(20).limitCount([0, 1]),
  LootEntry.of("powah:thermo_generator_basic").withWeight(20).limitCount([0, 1]),
  LootEntry.of("powah:furnator_starter").withWeight(20).limitCount([0, 1]),
  LootEntry.of("powah:solar_panel_starter").withWeight(20).limitCount([0, 1]),
  LootEntry.of("powah:magmator_basic").withWeight(20).limitCount([0, 1]),
  LootEntry.of("powah:solar_panel_basic").withWeight(20).limitCount([0, 1]),
  LootEntry.of("powah:thermo_generator_starter").withWeight(20).limitCount([0, 1]),
  LootEntry.of("powah:magmator_starter").withWeight(20).limitCount([0, 1]),
      ]);
  });